version: '3.8'


services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: api_futebol
      MYSQL_USER: usuario_api
      MYSQL_PASSWORD: senha_segura
    ports:
      - "3306:3306"
